dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
addons:
    apt:
        packages:
            - rabbitmq-server
env:
    - DJANGO="Django>=1.11,<2.0"
    - DJANGO="Django>=2.1,<2.2"
    - DJANGO="Django>=2.2,<2.3"
    - DJANGO="Django>=3.0,<3.1"
jobs:
    exclude:
        - python: "3.5"
          env: DJANGO="Django>=3.0,<3.1"
        - python: "3.8-dev"
          env: DJANGO="Django>=1.11,<2.0"
        - python: "3.8-dev"
          env: DJANGO="Django>=2.1,<2.2"
install:
    # Force installation of Python 3.8 compatible pika -- remove once pika>1.1.0 is released
    - pip install git+https://github.com/pika/pika.git@cbc05fd8ccb04c3b4a5e99327d0dfd6fbd61e14d --upgrade
    - pip install -r requirements.txt -e .
    - pip install $DJANGO
    - pip install -r build_requirements.txt
script:
    - py.test
    - flake8 domain_events --max-line-length=120 --exclude=__init__.py
    - mypy domain_event_broker
    - sphinx-build -b html docs docs/_build/html
